"""API routes for the Dev Copilot."""

import json

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from arc_devkit.api.rate_limit import limiter
from arc_devkit.core.validation import MAX_PROMPT_CHARS

router = APIRouter()


class AskRequest(BaseModel):
    """Request body for the /copilot/ask endpoint."""

    prompt: str = Field(
        ...,
        min_length=3,
        max_length=MAX_PROMPT_CHARS,
        description="Question or instruction.",
    )


class AskResponse(BaseModel):
    """Dev Copilot response."""

    response: str = Field(..., description="Response generated by the model.")
    model: str = Field(..., description="Model identifier used.")


@router.post("/ask", response_model=AskResponse, summary="Ask the Dev Copilot")
@limiter.limit("20/minute")
async def ask(request: Request, body: AskRequest) -> AskResponse:
    """
    Send a question to Dev Copilot and return the complete response.

    Dev Copilot specializes in Arc blockchain development:
    Solidity, web3.py, USDC, Circle Agent Stack, and economic agents.
    """
    from arc_devkit.copilot.agent import DevCopilot

    try:
        copilot = DevCopilot()
        resposta = copilot.ask(body.prompt)
        return AskResponse(response=resposta, model=copilot.model)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


class AgentResponse(BaseModel):
    """Agentic Dev Copilot response."""

    response: str = Field(..., description="Final response after tool use.")
    model: str = Field(..., description="Model identifier used.")
    tool_calls: list[dict] = Field(default_factory=list, description="Tools invoked.")
    iterations: int = Field(0, description="Tool-use round-trips executed.")


@router.post("/agent", response_model=AgentResponse, summary="Agentic Dev Copilot (tool use)")
@limiter.limit("10/minute")
async def agent(request: Request, body: AskRequest) -> AgentResponse:
    """
    Answer using READ-ONLY on-chain tools (balance, gas, tx debugging, view calls).

    The model decides which tools to call; the toolkit executes them locally and
    the loop stops at a final answer or after the iteration limit. Tools never
    sign or broadcast transactions.
    """
    from arc_devkit.copilot.agent import DevCopilot

    try:
        copilot = DevCopilot()
        resultado = copilot.run_agent(body.prompt)
        return AgentResponse(model=copilot.model, **resultado)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@router.post("/ask/stream", summary="Dev Copilot SSE streaming")
@limiter.limit("10/minute")
async def ask_stream(request: Request, body: AskRequest) -> StreamingResponse:
    """
    Send a question and stream the response token by token via Server-Sent Events.

    Each event format: `data: {"token": "..."}\\n\\n`
    Final event: `data: {"done": true}\\n\\n`
    """
    from arc_devkit.copilot.agent import DevCopilot

    copilot = DevCopilot()

    def _generator():
        try:
            for chunk in copilot.ask_stream(body.prompt):
                payload = json.dumps({"token": chunk}, ensure_ascii=False)
                yield f"data: {payload}\n\n"
            yield 'data: {"done": true}\n\n'
        except Exception as exc:
            error_payload = json.dumps({"error": str(exc)})
            yield f"data: {error_payload}\n\n"

    return StreamingResponse(
        _generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )
