"""API routes for the Dev Copilot."""

import json

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

router = APIRouter()


class AskRequest(BaseModel):
    """Request body for the /copilot/ask endpoint."""

    prompt: str = Field(..., min_length=3, description="Question or instruction.")


class AskResponse(BaseModel):
    """Dev Copilot response."""

    response: str = Field(..., description="Response generated by the model.")
    model: str = Field(..., description="Model identifier used.")


@router.post("/ask", response_model=AskResponse, summary="Ask the Dev Copilot")
async def ask(body: AskRequest) -> AskResponse:
    """
    Send a question to Dev Copilot and return the complete response.

    Dev Copilot specializes in Arc blockchain development:
    Solidity, web3.py, USDC, Circle Agent Stack, and economic agents.
    """
    from arc_devkit.copilot.agent import DevCopilot

    try:
        copilot = DevCopilot()
        resposta = copilot.ask(body.prompt)
        return AskResponse(response=resposta, model=copilot.model)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@router.post("/ask/stream", summary="Dev Copilot SSE streaming")
async def ask_stream(body: AskRequest) -> StreamingResponse:
    """
    Send a question and stream the response token by token via Server-Sent Events.

    Each event format: `data: {"token": "..."}\\n\\n`
    Final event: `data: {"done": true}\\n\\n`
    """
    from arc_devkit.copilot.agent import DevCopilot

    copilot = DevCopilot()

    def _generator():
        try:
            for chunk in copilot.ask_stream(body.prompt):
                payload = json.dumps({"token": chunk}, ensure_ascii=False)
                yield f"data: {payload}\n\n"
            yield 'data: {"done": true}\n\n'
        except Exception as exc:
            error_payload = json.dumps({"error": str(exc)})
            yield f"data: {error_payload}\n\n"

    return StreamingResponse(
        _generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )
